### ISSUE TITLE
UpdateChecker でエラー出ない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/lightning-g3-evergreen#49]
G3 Pro Unit とセットで有効化するプラグイン

ダッシュボード開いた時に最初だけ表示されるんだけど僕だけ？
（再読み込みすると消える）

Deprecated: Creation of dynamic property YahnisElsts\PluginUpdateChecker\v5p0\Plugin\PluginInfo::$request_time_elapsed is deprecated in /var/www/html/wp-content/plugins/lightning-g3-evergreen/vendor/yahnis-elsts/plugin-update-checker/Puc/v5p0/Metadata.php on line 55 Deprecated: Creation of dynamic property YahnisElsts\PluginUpdateChecker\v5p1\Plugin\PluginInfo::$request_time_elapsed is deprecated in /var/www/html/wp-content/plugins/vk-blocks/vendor/yahnis-elsts/plugin-update-checker/Puc/v5p1/Metadata.php on line 55 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/lightning-g3-evergreen/vendor/yahnis-elsts/plugin-update-checker/Puc/v5p0/Metadata.php:55) in /var/www/html/wp-admin/admin-header.php on line 9

**Comment by kurudrive** [comment]
引き続き

```
Deprecated: Creation of dynamic property YahnisElsts\PluginUpdateChecker\v5p0\Plugin\PluginInfo::$request_time_elapsed is deprecated in /var/www/html/wp-content/plugins/lightning-g3-evergreen/vendor/yahnis-elsts/plugin-update-checker/Puc/v5p0/Metadata.php on line 55 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/lightning-g3-evergreen/vendor/yahnis-elsts/plugin-update-checker/Puc/v5p0/Metadata.php:55) in /var/www/html/wp-admin/admin-header.php on line 9
```

**Comment by MasayaMORIMOTO** [comment]
マージされたようなので Close します。ありがとうございました。
